// Generated by Selenium IDE

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.Keys;

import java.util.*;

public class LoginTest extends BaseTest {

    @Test
    public void loginPositive() {
    LoginPage loginPage = new LoginPage(driver);
        driver.findElement(By.cssSelector("em:nth-child(1)")).click();
        driver.findElement(By.cssSelector("em:nth-child(1)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("em:nth-child(1)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("tomsmith");
        driver.findElement(By.cssSelector("em:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".subheader")).click();
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("SuperSecretPassword!");
        driver.findElement(By.cssSelector(".fa")).click();
        {
            List<WebElement> elements = driver.findElements(By.id("flash"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void loginNegative() {

        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("TestTest");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("TestTest");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        {
            List<WebElement> elements = driver.findElements(By.id("flash"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".fa"));
            assert (elements.size() > 0);
        }
    }
}
